version: '3.7'

services:

  # bee-queue Queue.createJob()
  client:
    image: stress-beequeue
    command: node src/client.js
    environment:
    - REDIS_HOST=redis
    - BEEQUEUE_NUMCHAINS=11
    - BEEQUEUE_INTERVAL=500
    #- BEEQUEUE_RANDOM_DELAY=15
    - BEEQUEUE_FAIL_PERCENT=10
    - BEEQUEUE_CLIENT

#    environment:
#      REDIS_HOST: redis
#      BEEQUEUE_NUMCHAINS: '23'
#      BEEQUEUE_INTERVAL: '500'
#      BEEQUEUE_RANDOM_DELAY: '15'

  # bee-queue Queue.process()
  server:
    image: stress-beequeue
    environment:
    - REDIS_HOST=redis
    - BEEQUEUE_CONCURRENCY=3
    - BEEQUEUE_FASTEST=0
    - BEEQUEUE_VERBOSE=0

#    - BEEQUEUE_RANDOM_DELAY=1


  redis:
    image: redis:alpine
    volumes:
    - ./.redisData:/data
